# WARNING: this may not be 100% production ready, but it's a good start.
version: '3.3'

services:

  web:
    #    image: api
    build: .
    command: gunicorn -b 0.0.0.0:5000 api.wsgi:app
    env_file:
      - ./.flaskenv
    volumes:
      - ./api:/code/api
      - ./migration:/code/migration
    expose:
      - 5000

